const mongoose = require('mongoose');

const cryptoPriceSchema = new mongoose.Schema({
  date: { type: Date, default: Date.now },
  prices: {
    bitcoin: { usd: Number },
    ethereum: { usd: Number },
    tether: { usd: Number },
    binancecoin: { usd: Number },
    solana: { usd: Number },
    'usd-coin': { usd: Number },
    xrp: { usd: Number },
    toncoin: { usd: Number },
    dogecoin: { usd: Number },
    cardano: { usd: Number },
    tron: { usd: Number },
    'wrapped-bitcoin': { usd: Number },
    'shiba-inu': { usd: Number },
    'avalanche-2': { usd: Number },
    polkadot: { usd: Number },
    chainlink: { usd: Number },
    'bitcoin-cash': { usd: Number },
    near: { usd: Number },
    uniswap: { usd: Number },
    polygon: { usd: Number },
    litecoin: { usd: Number },
    dai: { usd: Number },
    'leo-token': { usd: Number },
    pepe: { usd: Number },
    kaspa: { usd: Number },
    'internet-computer': { usd: Number },
    'ethereum-classic': { usd: Number },
    aptos: { usd: Number },
    monero: { usd: Number },
    hedera: { usd: Number },
    'render-token': { usd: Number },
    cosmos: { usd: Number },
    stellar: { usd: Number },
    mantle: { usd: Number },
    'first-digital-usd': { usd: Number },
    okb: { usd: Number },
    'fetch-ai': { usd: Number },
    'immutable-x': { usd: Number },
    'pancakeswap-token': { usd: Number },
    'eth-2-staking-by-pooltogether': { usd: Number },
    'binance-usd': { usd: Number },
    usde: { usd: Number },
    aave: { usd: Number },
    'elrond-erd-2': { usd: Number },
    helium: { usd: Number },
    chiliz: { usd: Number },
    'quant-network': { usd: Number },
    celo: { usd: Number },
    'curve-dao-token': { usd: Number },
    'theta-token': { usd: Number }
  }
});

module.exports = mongoose.model('CryptoPrice', cryptoPriceSchema);
